---
- hosts: docker
  remote_user: root
  tasks:
  - name: install epel-release
    yum: name={{ item }} state=latest
    with_items:
     - epel-release
  - name: install systemd
    yum: name=systemd state=installed update_cache=yes
    when: ansible_os_family == "RedHat"
  #- name: install systemd
  #  yum: name={{ item }} state=latest
  #  with_items:
  #   - systemd
  - name: install collectd
    yum: name={{ item }} state=latest
    with_items:
     - collectd
     - collectd-rrdtool
  - name: copy collectd.conf
    template: src=collectd.conf dest=/etc/collectd.conf
  - name: copy init.d/collectd
    template: src=collectd dest=/etc/init.d/collectd owner=root group=root mode=0755
  - name: copy rc.d/init.d/collectd
    template: src=collectd dest=/etc/rc.d/init.d/collectd owner=root group=root mode=0755
    notify: 
     - restart collectd
