gem install CFPropertyList -v '2.3.2'
gem install Platform -v '0.4.0'
gem install ansi -v '1.3.0'
gem install builder -v '3.2.2'
gem install ffi -v '1.9.10'
gem install childprocess -v '0.5.7'
gem install diff-lcs -v '1.2.5'
gem install eventmachine -v '1.0.8'
gem install mixlib-log -v '1.6.0'
gem install uuidtools -v '2.1.5'
gem install gssapi -v '1.2.0'
gem install gyoku -v '1.3.1'
gem install httpclient -v '2.6.0.1'
gem install little-plugger -v '1.1.4'
gem install multi_json -v '1.11.2'
gem install logging -v '1.8.2'
gem install nori -v '2.6.0'
gem install rubyntlm -v '0.4.0'
gem install winrm -v '1.3.4'
gem install em-winrm -v '0.7.0'
gem install excon -v '0.45.4'
gem install fission -v '0.5.0'
gem install formatador -v '0.2.5'
gem install mime-types -v '1.25.1'
gem install net-ssh -v 2.9.2
gem install net-scp -v '1.2.1'
gem install fog-core -v '1.32.1'
gem install fog-json -v '1.0.2'
gem install ipaddress -v '0.8.0'
gem install xml-simple -v '1.1.5'
gem install fog-aliyun -v '0.0.10'
gem install mini_portile -v '0.6.2'
gem install nokogiri -v '1.6.6.2'
gem install fog-xml -v '0.1.2'
gem install fog-atmos -v '0.1.0'
gem install fog-aws -v '0.7.6'
gem install inflecto -v '0.0.2'
gem install fog-brightbox -v '0.9.0'
gem install fog-dynect -v '0.0.2'
gem install fog-ecloud -v '0.3.0'

gem install fog-google -v '0.1.0'
gem install fog-local -v '0.2.1'
gem install fog-powerdns -v '0.1.1'
gem install fog-profitbricks -v '0.0.5'
gem install fog-radosgw -v '0.0.4'
gem install fog-riakcs -v '0.1.0'
gem install fog-sakuracloud -v '1.3.3'
gem install fog-serverlove -v '0.1.2'
gem install fog-softlayer -v '1.0.0'
gem install fog-storm_on_demand -v '0.1.1'
gem install fog-terremark -v '0.1.0'
gem install fog-vmfusion -v '0.1.0'
gem install fog-voxel -v '0.1.0'
gem install fog -v '1.34.0'
gem install gem-content -v '1.0.0'
gem install posix-spawn -v '0.3.11'
gem install grit -v '2.5.0'

gem install highline -v 1.7.8
gem install i18n -v  0.7.0
gem install json -v  1.8.3
gem install open4 -v  1.3.4
gem install os -v  0.9.6
gem install popen4 -v 0.1.2
gem install progressbar -v  0.21.0
gem install ruby-vnc -v  1.0.1
gem install thor 0.19.1
gem install to_slug 1.0.8
