- hosts: collectdclient
  roles:
    - { role: centos, when: "ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'" }
    - { role: ubuntu, when: "ansible_distribution == 'Ubuntu'" }
