- hosts: collectdclient
  roles:
    - { role: centos7, when: "ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'" }
    - { role: ubuntu1404, when: "ansible_distribution == 'Ubuntu'" }
