  - name: clean existing website content
    shell: rm -rf {{webapp}}/test11 && rm -f {{webapp}}/test11.war 
  - name: ensure tomcat6 is running
    service: name=tomcat6 state=started
  - name: copy webapp
    copy: src=HelloTomcat/test11.war dest={{webapp}}/ owner=tomcat group=tomcat
  - name: sleep for 5 seconds
    shell: /bin/sleep 5
  - name: copy mysql.properties
    template: src=mysql.properties dest={{webapp}}/test11/WEB-INF/classes/mysql.properties  owner=tomcat group=tomcat mode=0644
    notify: restart tomcat6
